[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bachgen"
version = "0.1.0"

[tool.setuptools]
packages = ["bachgen"]

[tool.setuptools.packages.find]
where = ["."]
include = ["bachgen*"]